### ISSUE TITLE
Change to table layout with rows for each developer

### ISSUE THREAD

**Issue by wiz** [dennisreimann/bitcoindevlist.com#32]
The current UI design feels a bit unbalanced with uneven empty spaces, maybe consider changing to a more structured table layout?

**Comment by Giszmo** [comment]
I guess the problem is the varying length of bios. That could be improved by limiting them all to 5 lines that expand on click for example. Also the tags should move between donate button and bio to make the layout calmer.

Take this for example:

![Screenshot from 2020-12-08 12-54-11](https://user-images.githubusercontent.com/96378/101506867-a7c9fa00-3954-11eb-9a7d-d2742b70c421.png)

Wouldn't this be better?

![Screenshot from 2020-12-08 13-01-27](https://user-images.githubusercontent.com/96378/101507626-84537f00-3955-11eb-8a73-81245b9964c8.png)

(please ignore the weird background coloring. Don't know where that came from when editing the html/css in the browser)

**Comment by dennisreimann** [comment]
@Giszmo Good call, will consider that!

**Comment by Giszmo** [comment]
The reload is a bit disruptive. If you want to just go through the list and read up on some of the donatees, you probably want the information to just expand, especially as the sort order is random.

**Comment by Giszmo** [comment]
Also my GitHub link disappeared! :(

**Comment by dennisreimann** [comment]
Ok, will give expanding in place a look during the next days. For now it's GitHub or GitLab :)

**Comment by dennisreimann** [comment]
@Giszmo fixed :)

**Comment by Giszmo** [comment]
Much better now! Thanks so much!

**Comment by dennisreimann** [comment]
Thanks again for your input! :)
