### ISSUE TITLE
Add a way to receive donations without counter-party risk?

### ISSUE THREAD

**Issue by siwatanejo** [dennisreimann/bitcoindevlist.com#67]
First of all, thank you for this initiative. Just wanted to ask a simple question: given that bitcoin's ethos is trustlessness, could you develop a way to donate without having to trust the developers of this website to channel the funds through them? I suppose this doesn't work this way because the json files provided don't include a bitcoin address or LN node URI.

**Comment by dennisreimann** [comment]
Hey, we aren't funneling anything through, because we aren't collecting the donations via this site. We are just providing an overview of contributors who accept donations via their own/self-hosted methods (like BTCPay Server). 

This site isn't a centralized solution for collecting donations, just a bunch of contributor profiles with links to their individual donation pages.

**Comment by siwatanejo** [comment]
Oh sorry I guess I clicked on one of the donate buttons and it seemed to me that I was still in the same website, my bad.
